### ISSUE TITLE
Cannot Delete SERVER cert

### ISSUE THREAD

**Issue by afiz** [opencoff/certik#1]
i can delete the cert if the cert is user/client type:
```
certik mycert.db delete testclientcert
Don't forget to generate a new CRL (certik mycert.db crl)
```

But if the cert is server type, it will result in error:
```
certik mycert.db delete testservercert
certik: no such CN
```

**Comment by opencoff** [comment]
Fixed bug in go-pki (dependency); please update to latest tip of tree (v0.7.2) and try. Thanks!

**Comment by afiz** [comment]
I just tested and now it works: i can delete SERVER type cert. Excellent! Thanks!
